import { p1, p10, p11, p2, p3, p4, p6, p7, p8, p9 } from "../images";

const cardsData = [
  {
    id:1,
    itemName: "camera",
    titl: "Stylish Canon American Camera",
    newPrice: 12000,
    oldPrice: 18000,
    img: p1,
  },
  {
    id:2,
    itemName: "Bottle",
    titl: "Stylish Bottle for cold drinks ,water",
    newPrice: 1200,
    oldPrice: 1800,
    img: p2,
  },
  {
    id:3,
    itemName: "Thai Bottle",
    titl: "Stylish Thai Bottle for cold drinks ,water",
    newPrice: 1900,
    oldPrice: 3000,
    img: p3,
  },
  {
    id:4,
    itemName: "Thai Bottle",
    titl: "Stylish Thai Bottle for Coffee",
    newPrice: 1900,
    oldPrice: 3000,
    img: p4,
  },
  {
    id:5,
    itemName: "Thai Bottle",
    titl: "Stylish Thai Bottle for water",
    newPrice: 1900,
    oldPrice: 3000,
    img: p6,
  },
  {
    id:6,
    itemName: "Thai Bottle",
    titl: "Stylish Thai Bottle for water",
    newPrice: 1900,
    oldPrice: 3000,
    img: p7,
  },
  {
    id:7,
    itemName: "Thai Bottle",
    titl: "Army Thai Bottle for water",
    newPrice: 1900,
    oldPrice: 3000,
    img: p8,
  },
  {
    id:8,
    itemName: "Thai Bottle",
    titl: "Kids Bottle for Milk",
    newPrice: 1900,
    oldPrice: 3000,
    img: p9,
  },
  {
    id:10,
    itemName: "Thai Bottle",
    titl: "Kids Bottle for Milk",
    newPrice: 1900,
    oldPrice: 3000,
    img: p10,
  },
  {
    id:11,
    itemName: "Thai Bottle",
    titl: "Kids Bottle for Milk",
    newPrice: 1900,
    oldPrice: 3000,
    img: p11,
  },
];
export default cardsData;